#! /bin/sh
# Start/stop the RF Interference Monitoring System software (RFIMS), of the China-Argentina RadioTelescope (CART)

### BEGIN INIT INFO
# Provides:          rfims-cart
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start the program rfims-cart
# Description:       rfims-cart is a software intended to get RF power measurements from a spectrum analyzer
#					 which is connected to an antenna that is able to change its azimuth angle and its
#					 polarization, to analize the RF interferences (RFI) which are present around the
#					 China-Argentina RadiosTelescope.
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
	echo "Before running the software rfims-cart, it will be waited 30 s to ensure the USB devices to be ready."
	
	sleep 30 #30 s

	echo "\nStarting rfims-cart..."
	nice -n -10 /usr/local/bin/rfims-cart --plot --rfi=ska-mode1
	#/usr/local/bin/rfims-cart --plot --rfi=ska-mode1
    ;;
  stop)
    echo "Stopping rfims-cart"
    killall rfims-cart
    ;;
  *)
    echo "Usage: /etc/init.d/rfims-cart-boot {start|stop}"
    exit 1
    ;;
esac

exit 0
